<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3.2 (Python 3.13.5 on win32)" generated="2025-07-20T11:06:30.527280" rpa="false" schemaversion="5">
<suite id="s1" name="Home" source="C:\QAx\projects\yodapp-robot\tests\home.robot">
<test id="s1-t1" name="Deve abrir a tela principal" line="7">
<kw name="Open Application" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2025-07-20T11:06:52.850027" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2025-07-20T11:06:52.849763" elapsed="0.004042">No application is open</status>
</kw>
<msg time="2025-07-20T11:06:52.854488" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2025-07-20T11:06:52.854919" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
    at getResponseForW3CError (C:\Users\Lucas\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\Lucas\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:487:57)</msg>
<arg>http://localhost:4723</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Android Emulator</arg>
<arg>automationName=UIAutomator2</arg>
<arg>app=${EXECDIR}/app/yodapp-beta.apk</arg>
<arg>udid=emulator-5554</arg>
<arg>autoGrantPermissions=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://appium.io/docs/en/2.1/cli/args/
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2025-07-20T11:06:30.681092" elapsed="22.175178">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
    at getResponseForW3CError (C:\Users\Lucas\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\Lucas\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:487:57)</status>
</kw>
<kw name="Wait Until Page Contains" owner="AppiumLibrary">
<arg>Yodapp</arg>
<doc>Waits until `text` appears on current page.</doc>
<status status="NOT RUN" start="2025-07-20T11:06:52.856653" elapsed="0.000049"/>
</kw>
<kw name="Wait Until Page Contains" owner="AppiumLibrary">
<arg>Mobile Training</arg>
<doc>Waits until `text` appears on current page.</doc>
<status status="NOT RUN" start="2025-07-20T11:06:52.857390" elapsed="0.000038"/>
</kw>
<kw name="Wait Until Page Contains" owner="AppiumLibrary">
<arg>by Papito</arg>
<doc>Waits until `text` appears on current page.</doc>
<status status="NOT RUN" start="2025-07-20T11:06:52.858018" elapsed="0.000040"/>
</kw>
<kw name="Close Application" owner="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<status status="NOT RUN" start="2025-07-20T11:06:52.858430" elapsed="0.000031"/>
</kw>
<status status="FAIL" start="2025-07-20T11:06:30.680298" elapsed="22.178530">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms
    at getResponseForW3CError (C:\Users\Lucas\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1143:9)
    at asyncHandler (C:\Users\Lucas\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:487:57)</status>
</test>
<status status="FAIL" start="2025-07-20T11:06:30.528406" elapsed="22.331284"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Home" id="s1" pass="0" fail="1" skip="0">Home</stat>
</suite>
</statistics>
<errors>
<msg time="2025-07-20T11:06:52.854488" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
